Repository projectcleanroom/clean_adm_back, pull requests merged in 2024-08, with the labels that each got.

#3 refactor : application.properties 삭제
  .idea/dataSources.xml
Labels: bug

#5 feat/estumate
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCancelResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCreateRequestDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCreateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionUpdateRequestDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/MyCommissionResponseDto.java
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/commission/repository/CommissionRepository.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateCreateRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateCreateResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateDeleteResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateUpdateRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
  src/main/java/com/clean/cleanroom/partner/entity/Partner.java
  src/main/java/com/clean/cleanroom/partner/repository/PartnerRepository.java
  src/main/java/com/clean/cleanroom/util/JwtUtil.java
Labels: feat

#8 refactor : Custom Exception 보안적 위반사례 검토
  src/main/java/com/clean/cleanroom/exception/CustomException.java
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/exception/GlobalExceptionHandler.java
  src/main/java/com/clean/cleanroom/filter/JwtAuthenticationFilter.java
  src/main/java/com/clean/cleanroom/members/controller/MembersLoginAndLogoutController.java
  src/main/java/com/clean/cleanroom/members/service/MembersLoginService.java
  src/main/java/com/clean/cleanroom/util/JwtUtil.java
  src/main/java/com/clean/cleanroom/util/ResponseDto.java
Labels: refactor

#11 feat : 회원가입 API 추가
  .idea/dataSources.xml
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/partner/controller/PartnerController.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerGetProfileResponseDto.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerProfileResponseDto.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerRequestDto.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerSignupRequestDto.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerSignupResponseDto.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerUpdateRequestDto.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/partner/entity/Partner.java
  src/main/java/com/clean/cleanroom/partner/repository/PartnerRepository.java
  src/main/java/com/clean/cleanroom/partner/service/PartnerService.java
  src/main/resources/application.properties
Labels: feat

#13 rename :로그인 API 분리
  src/main/java/com/clean/cleanroom/partner/entity/Partner.java
Labels: rename

#15 rename : 코드수정
  src/main/java/com/clean/cleanroom/partner/dto/PartnerRequestDto.java
Labels: rename

#17 refactor : 코드 추가
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/partner/repository/PartnerRepository.java
  src/main/java/com/clean/cleanroom/partner/service/PartnerService.java
Labels: refactor

#18 feat : swagger partner 경로 설정 추가
  src/main/java/com/clean/cleanroom/config/SwaggerConfig.java
Labels: feat

#19 refactor : 견적 승인 필드 추가
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateCreateRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
Labels: refactor

#20 refactor : HouseType enums 수정
  src/main/java/com/clean/cleanroom/enums/HouseType.java
Labels: refactor

#22 refactor : logback-spring.xml 로컬 로깅 추가
  build.gradle
  src/main/resources/logback-spring.xml
Labels: feat

#23 feat : INFO 레벨 로그와 ERRROR레벨 로그를 파일로 저장.
  src/main/resources/logback-spring.xml
Labels: feat

#24 refactor : CleanType 필드 이름 수정
  src/main/java/com/clean/cleanroom/enums/CleanType.java
Labels: refactor

#25 Bug : 회원가입 오류 수정
  .idea/dataSources.xml
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/account/controller/AccountController.java
  src/main/java/com/clean/cleanroom/business/controller/BusinessInfoController.java
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/partner/controller/PartnerController.java
  src/main/java/com/clean/cleanroom/partner/controller/PartnerLoginAndLogoutController.java
  src/main/java/com/clean/cleanroom/partner/entity/Partner.java
  src/main/java/com/clean/cleanroom/partner/repository/PartnerRepository.java
  src/main/java/com/clean/cleanroom/partner/service/PartnerService.java
  src/main/resources/application.properties
Labels: bug

#27 refactor : 코드 수정
  src/main/java/com/clean/cleanroom/config/WebConfig.java
  src/main/java/com/clean/cleanroom/filter/JwtAuthenticationFilter.java
  src/main/resources/application.properties
Labels: refactor

#28 refactor : 불필요코드 주석 처리
  src/main/java/com/clean/cleanroom/members/controller/MembersController.java
  src/main/java/com/clean/cleanroom/members/controller/MembersLoginAndLogoutController.java
Labels: rename

#29 refactor : 환경별로 로그 전략을 분리
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: refactor

#32 hotfix : https 요청 경로 추가
  src/main/java/com/clean/cleanroom/config/SwaggerConfig.java
Labels: hotfix

#33 hotfix : 사용자서버->파트너서버 경로수정
  .idea/modules.xml
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/config/SwaggerConfig.java
Labels: hotfix

#35 Refactor/entity
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/account/entity/Account.java
  src/main/java/com/clean/cleanroom/business/entity/BusinessInfo.java
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/resources/application.properties
Labels: refactor

#36 refactor : house type enums 수정
  src/main/java/com/clean/cleanroom/enums/HouseType.java
Labels: refactor

#38 refactor : 비밀번호 변경 로직 수정
  .idea/dataSources.xml
  src/main/java/com/clean/cleanroom/CleanRoomApplication.java
  src/main/java/com/clean/cleanroom/partner/service/PartnerService.java
Labels: refactor

#39 refactor : 의뢰 Dto 수정
  .idea/dataSources.xml
  src/main/java/com/clean/cleanroom/commission/dto/CommissionListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
Labels: refactor

#40 refactor : 회원정보수정 로직 수정
  src/main/java/com/clean/cleanroom/account/controller/AccountController.java
  src/main/java/com/clean/cleanroom/partner/controller/PartnerController.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerUpdateProfileRequestDto.java
  src/main/java/com/clean/cleanroom/partner/entity/Partner.java
  src/main/java/com/clean/cleanroom/partner/service/PartnerService.java
  src/main/resources/application.properties
Labels: refactor

#41 refactor : 견적 작성 Dto 수정
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateCreateRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateCreateResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateUpdateRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
Labels: refactor

#42 refactor : 견적 수정, 조회 Dto 수정
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
Labels: refactor

#43 refactor : 견적 수정, 조회 Dto 수정
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateUpdateResponseDto.java
Labels: refactor

#44 feat : 견적 가격 수정 API
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimatePatchRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimatePatchResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateUpdateRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
Labels: refactor

#46 refactor : 견적 작성 Dto 수정
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateUpdateRequestDto.java
Labels: refactor

#49 refactor : 견적 삭제 Dto 수정
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateDeleteResponseDto.java
Labels: refactor

#50 refactor : 견적 patch Dto 수정
  src/main/java/com/clean/cleanroom/estimate/dto/EstimatePatchRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimatePatchResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
Labels: refactor

#51 refactor : statusType enums 추가
  src/main/java/com/clean/cleanroom/enums/StatusType.java
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateCreateResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimatePatchRequestDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimatePatchResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
Labels: refactor

#52 feat : 확정된 견적 내역 조회 API
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/repository/EstimateRepository.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
Labels: feat

#53 refactor : confirm list dto 수정
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateConfirmListResponseDto.java
Labels: refactor

#54 refactor : commission dto 수정
  src/main/java/com/clean/cleanroom/commission/dto/CommissionListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
Labels: refactor

#55 refactor : estimate dto 이미지 추가
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDto.java
Labels: refactor

#57 feat : 사업자등록번호 인증 기능 구현
  src/main/java/com/clean/cleanroom/business/controller/BusinessController.java
  src/main/java/com/clean/cleanroom/business/dto/BusinessValidateRequestDto.java
  src/main/java/com/clean/cleanroom/business/dto/BusinessValidateResponseDto.java
  src/main/java/com/clean/cleanroom/business/entity/Business.java
  src/main/java/com/clean/cleanroom/business/repository/BusinessRepository.java
  src/main/java/com/clean/cleanroom/business/service/BusinessService.java
  src/main/java/com/clean/cleanroom/config/RestTemplateConfig.java
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/filter/JwtAuthenticationFilter.java
Labels: feat

#58 feat : imgupload add
  .idea/compiler.xml
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/partner/controller/PartnerController.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerUploadGetResponseDto.java
  src/main/java/com/clean/cleanroom/partner/dto/PartnerUploadResponseDto.java
  src/main/java/com/clean/cleanroom/partner/service/PartnerService.java
Labels: feat

#59 Feat/business
  src/main/java/com/clean/cleanroom/business/dto/BusinessValidateRequestDto.java
Labels: refactor

#60 refactor : SOLID 단일 책임 원칙 맞춰 수정
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
Labels: refactor

#61 refactor : 진위여부 request Dto 수정
  src/main/java/com/clean/cleanroom/business/dto/BusinessValidateRequestDto.java
Labels: refactor

#63 refactor : 견적 생성 공간복잡도 개선
  src/main/java/com/clean/cleanroom/commission/dto/CommissionEstimateDetailsDto.java
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/commission/repository/CommissionRepository.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateCreateResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
Labels: refactor
